### ISSUE TITLE
QuotaExceeded error

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/mslearn-aspnet-core#183] opened 2023-10-11 11:43 UTC
I saw no mention of this in existing issues or searching online (perhaps specific to my environment/subscription?)

I went through the [learn module](https://learn.microsoft.com/en-us/training/modules/microservices-aspnet-core/3-deploy-application) and after "Install the app", step 5 ("Run the quickstart script"), I see the following in the terminal...

```
> az aks create -n eshop-learn-aks -g test-eshop -c 1 --node-vm-size Standard_D4_v5 --vm-set-type VirtualMachineScaleSets -l westus --enable-managed-identity --generate-ssh-keys -o json

ERROR: (QuotaExceeded) Provisioning of resource(s) for container service eshop-learn-aks... failed. Message: Operation could not be completed as it results in exceeding approved standardDv5Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: westus, Current Limit: 0, Current Usage: 0, Additional Required: 4, (Minimum) New Limit Required: 4. Submit a request for Quota increase at {snipped} by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/per-vm-quota-requests. 
Code: QuotaExceeded
```

My Quotas shows at most 2/10 used.  The default vm template (Standard_D2_v5) only requests 2 vpus, I tried a 4 vcpu vm with same results (copied above).  I tried provisioning to westus too (in the event that the vm just wasn't available in that region somehow)

**Comment by masoudmm** [comment] 2023-10-22 13:14
I am using student azure subscription and I changed the vmSize to Standard_D4s_v3 in modules ->microservices-aspnet-core -> deploy -> k8s -> create-aks.cs file as I didn't have enough Quota for Standard_D2_v5 and when I sent the request to increase Quota, the azure turned me down.

You can test another valid vm size by clicking the "allSizes" link below vm size in create vm page. as long as it has >2 vCores and >4 Gb Ram.

I tested the B and F series vm sizes but the services would just fail after initial success in deployment, so far the Standard_D4s_v3  was good for me

**Comment by nikmaxott** [comment] 2023-11-29 10:47
@masoudmm That worked brilliantly, thanks! Although now I'm running into an error with the script where 

"ERROR: The resource with name 'eshoplearn20231129104523711' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription '<subscriptionID>'.

ERROR! ACR server eshoplearn20231129104523711 doesn't exist!"

**Comment by masoudmm** [comment] 2023-12-04 09:53
@nikmaxott 

I got this error a couple of times when I try to deploy the coupon api changes, and as I am still in training I didn't found a logical explanation yet, but when I undo the repository code changes (caused by your changes, helm script and ...) and start over, it is working again

**Comment by CamSoper** [comment] 2024-07-01 20:39
Closing as these scripts have been retired

**Closed as completed by CamSoper** 2024-07-01 20:39 UTC
